if SERVER then return end
surface.CreateFont( "CelestiaHUDFont", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 5 ),
    weight = 600,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaContextInformation", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 5 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaAdminTexT", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 10 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaAdminTexT2", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 8 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaContextTitle", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 12 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaContextButton", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 6 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaHUDTebex", {
    font = "Averta-Semibold",
    extended = false,
    size =  ScreenScale( 4 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )