if SERVER then return end
surface.CreateFont( "CelestiaContextInformation", {
    font = "Lato",
    extended = false,
    size =  ScreenScale( 5 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaContextTitle", {
    font = "Lato",
    extended = false,
    size =  ScreenScale( 12 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont( "CelestiaContextButton", {
    font = "Lato",
    extended = false,
    size =  ScreenScale( 6 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
} )

surface.CreateFont("CelestiaContextButtonSmall", {
    font = "Lato",
    extended = false,
    size =  ScreenScale( 6 ),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
})